---
sidebar: sidebar 
permalink: genai-engine-instance.html 
keywords: genai engine, instance, ec2, role, iam role, permissions, security group, inbound, outbound, private endpoints 
summary: Bei der Implementierung der GenAI-Infrastruktur erstellt die Workload Factory eine EC2 Instanz für die GenAI Engine. Außerdem werden für diese Instanz eine IAM-Rolle, eine Sicherheitsgruppe und private Endpunkte erstellt. Vielleicht möchten Sie mehr Details zu diesen Komponenten erfahren, die von den Workloads in Ihrer AWS-Umgebung werksseitig erstellt werden. 
---
= Komponenten für die NetApp GenAI Engine
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Bei der Implementierung der GenAI-Infrastruktur erstellt die Workload Factory eine EC2 Instanz für die GenAI Engine. Außerdem werden für diese Instanz eine IAM-Rolle, eine Sicherheitsgruppe und private Endpunkte erstellt. Vielleicht möchten Sie mehr Details zu diesen Komponenten erfahren, die von den Workloads in Ihrer AWS-Umgebung werksseitig erstellt werden.

EC2 Instanztyp:: m5.large
IAM-Rolle:: Die GenAI-Engine-Instanz benötigt die Berechtigungen, um Datenblöcke an das Einbettungsmodell in Amazon Bedrock zu senden und mit dem NetApp AI Service Back-End zu kommunizieren. Die IAM-Rolle umfasst die folgenden Berechtigungen:
+
--
.IAM-Rollenberechtigungen
[%collapsible]
====
[source, json]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ssm:DescribeDocument",
        "ssm:DescribeAssociation",
        "ssm:GetDeployablePatchSnapshotForInstance",
        "ssm:GetManifest",
        "ssm:ListInstanceAssociations",
        "ssm:ListAssociations",
        "ssm:PutInventory",
        "ssm:PutComplianceItems",
        "ssm:PutConfigurePackageResult",
        "ssm:UpdateAssociationStatus",
        "ssm:UpdateInstanceAssociationStatus",
        "ssm:UpdateInstanceInformation",
        "ssmmessages:CreateControlChannel",
        "ssmmessages:CreateDataChannel",
        "ssmmessages:OpenControlChannel",
        "ssmmessages:OpenDataChannel"
      ],
      "Resource": "*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "ssm:GetParameter"
      ],
      "Resource": "arn:aws:ssm:*:*:parameter/netapp/wlmai/*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "fsx:DescribeVolumes",
        "fsx:DescribeStorageVirtualMachines",
        "fsx:DescribeFileSystems"
      ],
      "Resource": "*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "fsx:TagResource",
        "fsx:ListTagsForResource"
      ],
      "Resource": [
        "arn:aws:fsx:*:*:storage-virtual-machine/*/*",
        "arn:aws:fsx:*:*:volume/*/*"
      ],
      "Effect": "Allow"
    },
    {
      "Action": [
        "fsx:CreateVolume"
      ],
      "Resource": [
        "arn:aws:fsx:*:*:volume/*/*",
        "arn:aws:fsx:*:*:storage-virtual-machine/*/*"
      ],
      "Effect": "Allow"
    },
    {
      "Condition": {
        "StringLike": {
          "aws:ResourceTag/netapp:wlmai:c92e9ed6-dcbb-45f7-95f0-58647ebec9d7:kbId": "*"
        }
      },
      "Action": "fsx:DeleteVolume",
      "Resource": [
        "arn:aws:fsx:*:*:volume/*/*",
        "arn:aws:fsx:*:*:backup/*"
      ],
      "Effect": "Allow"
    },
    {
      "Condition": {
        "StringLike": {
          "aws:ResourceTag/netapp:wlmai:c92e9ed6-dcbb-45f7-95f0-58647ebec9d7": "*"
        }
      },
      "Action": "fsx:UntagResource",
      "Resource": "arn:aws:fsx:*:*:storage-virtual-machine/*/*",
      "Effect": "Allow"
    },
    {
      "Condition": {
        "StringLike": {
          "aws:ResourceTag/netapp:wlmai:c92e9ed6-dcbb-45f7-95f0-58647ebec9d7:kbId": "*"
        }
      },
      "Action": "fsx:UntagResource",
      "Resource": "arn:aws:fsx:*:*:volume/*/*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "bedrock:InvokeModel",
        "bedrock:Rerank"
      ],
      "Resource": "*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "iam:PassRole"
      ],
      "Resource": [
        "arn:aws:iam::*:role/NetApp_AI_Bedrock_wlmai-*"
      ],
      "Effect": "Allow"
    },
    {
      "Action": [
        "ec2messages:GetMessages",
        "ec2messages:GetEndpoint",
        "ec2messages:AcknowledgeMessage",
        "ec2messages:DeleteMessage",
        "ec2messages:FailMessage",
        "ec2messages:SendReply"
      ],
      "Resource": "*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "logs:DescribeLogGroups"
      ],
      "Resource": "*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "logs:DescribeLogStreams",
        "logs:PutLogEvents",
        "logs:CreateLogStream",
        "logs:CreateLogGroup"
      ],
      "Resource": [
        "arn:aws:logs:*:*:log-group:/netapp/wlmai/*:log-stream:*",
        "arn:aws:logs:*:*:log-group:/netapp/wlmai/*"
      ],
      "Effect": "Allow"
    }
  ]
}
----
====
--
Sicherheitsgruppe:: Die Regeln für ausgehende Anrufe sind für den gesamten Datenverkehr offen, während die Regeln für eingehende Anrufe vollständig geschlossen sind.
Private Endpunkte:: Wenn die Ziel-VPC nicht bereits vorhanden ist, erstellt die Workload-Fabrik private Endpunkte für die EC2-Instanz der GenAI Engine, sodass die IT mit den folgenden AWS-Services kommunizieren kann:
+
--
* Amazonas-Grundgestein
+
** Grundgestein
** Bedrock-Runtime
** Bedrock-Agent-Runtime


* Amazon Elastic Container Registry (ECR)
+
** API
** docker


* AWS System Manager (SSM)
+
** SSM
** ec2messages
** Ssmbotschaften


* Amazon FSX für NetApp ONTAP
* Amazon CloudWatch


--

