---
settings:
  name: GenAI
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: GenAI-Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr über die Workload-Fabrik für GenAI
      url: "/ai-workloads-overview.html"
    - title: Schnellstart
      url: "/quick-start.html"
    - title: GenAI-Anforderungen
      url: "/requirements.html"
    - title: Ermittlung von Datenquellen für Ihre Wissensdatenbank
      url: "/identify-data-sources.html"
    - title: Implementierung der Knowledge Base Infrastruktur
      url: "/deploy-infrastructure.html"
    - title: Verwenden Sie die externe Chatbot-Beispielanwendung
      url: "/example-chatbot-application.html"
    - title: Komponenten für die NetApp GenAI Engine
      url: "/genai-engine-instance.html"
  - title: Nutzen Sie GenAI, um Wissensdatenbanken aufzubauen
    entries:
    - title: Erstellen einer Wissensdatenbank
      url: "/create-knowledgebase.html"
    - title: Testen Sie eine Wissensdatenbank
      url: "/test-knowledgebase.html"
    - title: Aktivieren Sie die Authentifizierung
      url: "/activate-authentication.html"
    - title: Veröffentlichen Sie eine Wissensdatenbank
      url: "/publish-knowledgebase.html"
    - title: Erstellen Sie eine RAG-basierte KI-Applikation
      url: "/create-application.html"
    - title: Was Sie als Nächstes tun können
      url: "/whats-next.html"
  - title: GenAI verwalten
    entries:
    - title: Management der GenAI-Infrastruktur
      url: "/manage-infrastructure.html"
    - title: Management von Wissensdatenbanken
      url: "/manage-knowledgebase.html"
    - title: Managen von Datenquellen
      url: "/manage-data-source.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/support-registration.html"
    - title: Fehlerbehebung
      url: "/troubleshooting.html"
    - title: Holen Sie sich Hilfe
      url: "/get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory for AWS
  repo: workload-family
