---
settings:
  name: GenAI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: GenAI-Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
  - title: Erfahren Sie mehr über die BlueXP -Workload-Fabrik für GenAI
    entries:
    - title: Erfahren Sie mehr über die BlueXP -Workload-Fabrik für GenAI
      url: "/general/ai-workloads-overview.html"
    - title: Komponenten der NetApp GenAI Engine
      url: "/general/genai-engine-instance.html"
  - title: Mit GenAI können Sie Wissensdatenbanken für Amazon Bedrock aufbauen
    entries:
    - title: Los geht's
      entries:
      - title: Schnellstart
        url: "/knowledge-base/quick-start-knowledge-base.html"
      - title: Anforderungen an die Wissensdatenbank
        url: "/knowledge-base/requirements-knowledge-base.html"
      - title: Identifizieren von Datenquellen, die zu einer Wissensdatenbank hinzugefügt
          werden können
        url: "/knowledge-base/identify-data-sources-knowledge-base.html"
      - title: Implementierung der GenAI-Infrastruktur
        url: "/knowledge-base/deploy-infrastructure.html"
    - title: Erstellen einer Wissensdatenbank
      url: "/knowledge-base/create-knowledgebase.html"
    - title: Testen Sie eine Wissensdatenbank
      url: "/knowledge-base/test-knowledgebase.html"
    - title: Aktivieren Sie die Authentifizierung
      url: "/knowledge-base/activate-authentication.html"
    - title: Veröffentlichen Sie eine Wissensdatenbank
      url: "/knowledge-base/publish-knowledgebase.html"
    - title: Verwenden Sie die externe Chatbot-Beispielanwendung
      url: "/knowledge-base/example-chatbot-application.html"
    - title: Erstellen Sie eine RAG-basierte KI-Applikation
      url: "/knowledge-base/create-application.html"
    - title: Was Sie als Nächstes tun können
      url: "/knowledge-base/whats-next.html"
  - title: Mit GenAI können Sie Konnektoren für Amazon Q Business erstellen
    entries:
    - title: Los geht's
      entries:
      - title: Schnellstart
        url: "/connector/quick-start-connector.html"
      - title: Anforderungen an Steckverbinder
        url: "/connector/requirements-connector.html"
      - title: Identifizieren von Datenquellen, die einem Konnektor hinzugefügt werden
          sollen
        url: "/connector/identify-data-sources-connector.html"
      - title: Implementierung der GenAI-Infrastruktur
        url: "/connector/deploy-infrastructure.html"
    - title: Erstellen Sie einen NetApp Connector für Amazon Q Business
      url: "/connector/define-connector.html"
  - title: Administration und Überwachung
    entries:
    - title: Management der GenAI-Infrastruktur
      url: "/general/manage-infrastructure.html"
    - title: Management von Wissensdatenbanken
      url: "/knowledge-base/manage-knowledgebase.html"
    - title: Verwalten von Konnektoren
      url: "/connector/manage-connector.html"
    - title: Managen von Datenquellen
      url: "/general/manage-data-source.html"
    - title: Überwachen Sie den Betrieb mit Tracker
      url: "/general/monitor-operations.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/support-registration.html"
    - title: Fehlerbehebung
      url: "/general/troubleshooting.html"
    - title: Holen Sie sich Hilfe
      url: "/get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
