---
settings:
  name: GenAI
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: GenAI-Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr über Workload Factory für GenAI
      url: "/ai-workloads-overview.html"
    - title: Schnellstart
      url: "/quick-start.html"
    - title: GenAI-Anforderungen
      url: "/requirements.html"
    - title: Ermittlung von Datenquellen für Ihre Wissensdatenbank
      url: "/identify-data-sources.html"
    - title: Implementierung der Knowledge Base Infrastruktur
      url: "/deploy-infrastructure.html"
  - title: Nutzen Sie GenAI, um Wissensdatenbanken zu erstellen
    entries:
    - title: Aufbau einer Wissensdatenbank
      entries:
      - title: Erstellen einer Wissensdatenbank
        url: "/create-knowledgebase.html"
      - title: Testen Sie eine Wissensdatenbank
        url: "/test-knowledgebase.html"
      - title: Aktivieren Sie die Authentifizierung
        url: "/activate-authentication.html"
      - title: Veröffentlichen Sie eine Wissensdatenbank
        url: "/publish-knowledgebase.html"
      - title: Was Sie als Nächstes tun können
        url: "/whats-next.html"
    - title: Managen von Datenquellen
      url: "/manage-data-source.html"
    - title: Management von Wissensdatenbanken
      url: "/manage-knowledgebase.html"
  - title: GenAI verwalten
    entries:
    - title: Management der GenAI-Infrastruktur
      url: "/manage-infrastructure.html"
    - title: Komponenten für die NetApp GenAI Engine
      url: "/genai-engine-instance.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP Workload Factory for AWS
  repo: workload-family
