= Klonen Sie eine Wissensdatenbank aus einem Snapshot
:allow-uri-read: 




=== Klonen Sie eine Wissensdatenbank aus einem Snapshot

NetApp Workload Factory für GenAI unterstützt jetzt das Klonen einer Wissensdatenbank aus einem Snapshot.  Dies ermöglicht die schnelle Wiederherstellung von Wissensdatenbanken und die Erstellung neuer Wissensdatenbanken mit vorhandenen Datenquellen und hilft bei der Datenwiederherstellung und -entwicklung.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#clone-a-knowledge-base["Klonen einer Wissensdatenbank"]



=== Erkennung und Replizierung von lokalen ONTAP Clustern

Entdecken und replizieren Sie lokale ONTAP Clusterdaten in ein FSx für ONTAP -Dateisystem, damit diese zur Anreicherung von KI-Wissensdatenbanken verwendet werden können.  Alle lokalen Erkennungs- und Replikations-Workflows sind über das neue Menü *On-Premises ONTAP* im Speicherinventar möglich.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/use-onprem-data.html["Ermitteln eines lokalen ONTAP Clusters"]
