= Benutzerdefinierter Snapshot-Name
:allow-uri-read: 




=== Benutzerdefinierter Snapshot-Name

Sie können jetzt einen Snapshot-Namen für einen Ad-hoc-Snapshot bereitstellen.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#protect-a-knowledge-base-with-snapshots["Schützen Sie eine Wissensdatenbank mit Snapshots"]



=== Individueller Name für die AI Engine Instance

Sie können der KI-Engine-Instanz jetzt während der Implementierung einen benutzerdefinierten Namen geben.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/deploy-infrastructure.html["Implementierung der GenAI-Infrastruktur"]



=== Wiederherstellung beschädigter oder fehlender GenAI-Infrastruktur

Wenn Ihre KI-Engine-Instanz beschädigt oder irgendwie gelöscht wird, können Sie sie von Workload Factory für Sie neu erstellen lassen.  Workload Factory fügt Ihre Wissensdatenbanken nach Abschluss des Neuaufbaus automatisch wieder an die Infrastruktur an, sodass sie einsatzbereit sind.

link:https://docs.netapp.com/us-en/workload-genai/general/troubleshooting.html["Fehlerbehebung"]
