---
sidebar: sidebar 
permalink: knowledge-base/create-knowledgebase.html 
keywords: ai, chatbot, creating, knowledge base 
summary: Nachdem Sie die KI-Infrastruktur bereitgestellt und die Datenquellen identifiziert haben, die Sie aus Ihren FSx for ONTAP -Datenspeichern in Ihre Wissensdatenbank integrieren möchten, können Sie mit dem Erstellen der Wissensdatenbank mithilfe von Workload Factory beginnen.  Im Rahmen dieses Schritts definieren Sie auch die KI-Eigenschaften und erstellen Gesprächseinstiege. 
---
= Einrichtung einer GenAI Knowledge Base
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die KI-Infrastruktur bereitgestellt und die Datenquellen identifiziert haben, die Sie aus Ihren FSx for ONTAP -Datenspeichern in Ihre Wissensdatenbank integrieren möchten, können Sie mit dem Erstellen der Wissensdatenbank mithilfe von Workload Factory beginnen.  Im Rahmen dieses Schritts definieren Sie auch die KI-Eigenschaften und erstellen Gesprächseinstiege.

Stellen Sie sicher, dass Ihre Umgebung den  für Wissensdatenbanken entsprichtlink:requirements-knowledge-base.html["Anforderungen"], bevor Sie fortfahren.

.Über diese Aufgabe
Wissensdatenbanken haben zwei Datenintegrationsmodalitäten - _public Mode_ und _Enterprise Mode_.

Öffentlicher Modus:: Eine Wissensdatenbank kann verwendet werden, ohne Datenquellen aus Ihrem Unternehmen zu integrieren. In diesem Fall liefert eine mit der Wissensdatenbank integrierte Anwendung nur Ergebnisse aus öffentlich zugänglichen Informationen im Internet. Dies wird als „_public Mode_“-Integration bezeichnet.
Enterprise-Modus:: In den meisten Fällen möchten Sie Datenquellen aus Ihrem Unternehmen in die Wissensdatenbank integrieren. Dies wird als _Enterprise Mode_ Integration bezeichnet, da es Wissen aus Ihrem Unternehmen liefert.
+
--
Datenquellen Ihrer Organisation können personenbezogene Daten (PII) enthalten.  Um diese vertraulichen Informationen zu schützen, können Sie beim Erstellen und Konfigurieren von Wissensdatenbanken _Datenleitplanken_ aktivieren.  Datenleitplanken, unterstützt durch NetApp Data Classification, identifizieren und maskieren personenbezogene Daten und machen sie so unzugänglich und unwiederbringlich.

link:https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["Erfahren Sie mehr über die NetApp Datenklassifizierung"^] .


NOTE: NetApp Workload Factory für GenAI maskiert keine sensiblen persönlichen Informationen (SPii).  Siehelink:https://docs.netapp.com/us-en/data-services-data-classification/reference-private-data-categories.html#types-of-sensitive-personal-data["Arten sensibler personenbezogener Daten"^] für weitere Informationen zu dieser Art von Daten.


NOTE: Datenleitplanken können jederzeit aktiviert oder deaktiviert werden.  Wenn Sie die Aktivierung von Datenleitplanken ändern, scannt Workload Factory die gesamte Wissensdatenbank von Grund auf neu, was Kosten verursacht.

--




== Erstellen und Konfigurieren der Wissensdatenbank

Die Wissensdatenbank definiert Eigenschaften wie die Bedrock-KI-Modelle und das Embedding-Format, mit denen Sie Ihre Wissensdatenbank erstellen möchten.

.Schritte
. Melden Sie sich bei Workload Factory mit einem der folgendenlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^] .
. Wählen Sie in der Kachel AI-Workloads *Deploy & manage* aus.
. Wählen Sie im Menü „Wissensdatenbanken und Konnektoren“ das Dropdown-Menü „Neu erstellen“ und wählen Sie „NetApp GenAI-Wissensdatenbank für Bedrock“ aus.
. Konfigurieren Sie auf der Seite „NetApp GenAI-Wissensdatenbank erstellen“ die Einstellungen für die Wissensdatenbank:


[discrete]
===== Details zur Wissensdatenbank

. *Name*: Geben Sie den Namen ein, den Sie für die Wissensdatenbank verwenden möchten.
. *Beschreibung*: Geben Sie eine detaillierte Beschreibung für die Wissensdatenbank ein.
. *Bedrock*: Wählen Sie die Region, in der Amazon Bedrock für Ihr AWS-Konto verfügbar ist.


[discrete]
===== Verschlucken

. *Einbettungsmodell*:
+
** Wählen Sie ein Einbettungsmodell zur Verwendung für die Wissensdatenbank aus.  Das Einbettungsmodell definiert, wie Ihre Daten in Vektoreinbettungen für die Wissensdatenbank konvertiert werden.  Workload Factory unterstützt die folgenden Modelle:
** Titan-Einbauteile G1 - Text
** Titan Einbettung Text v2
** Titan Multimodal Embeddings G1
** Englisch Einbetten
** Mehrsprachig Einbetten
+
Beachten Sie, dass Sie das Einbettungsmodell von Amazon Bedrock bereits aktiviert haben müssen.

+
https://aws.amazon.com/bedrock/titan/["Erfahren Sie mehr über Amazon Titan"^]

** Wählen Sie gegebenenfalls den Inferenztyp aus, der der Konfiguration des ausgewählten Einbettungsmodells entspricht.


. *Datenleitplanken*: Wählen Sie, ob Sie Datenleitplanken aktivieren oder deaktivieren möchten. link:https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["Erfahren Sie mehr über Datenleitplanken, unterstützt durch NetApp Data Classification"^] .
+
Die folgenden Voraussetzungen müssen erfüllt sein, um die Data Guardrails zu aktivieren.

+
** Für die Kommunikation mit NetApp Data Classification ist ein Servicekonto erforderlich.  Für die Erstellung eines Dienstkontos müssen Sie in Ihrem NetApp Console-Mandantenkonto über die Rolle „Organisationsadministrator“ verfügen.  Ein Mitglied mit der Rolle des Organisationsadministrators kann alle Aktionen in der ausführen.link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html#add-a-role-to-a-member["Erfahren Sie, wie Sie einem Mitglied in der NetApp -Konsole eine Rolle hinzufügen"^]
** Die KI-Engine muss Zugriff auf dielink:https://api.bluexp.netapp.com["NetApp Console API-Endpunkt"^] .
** Sie müssen Folgendes tun, wie inlink:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-cloud-compliance.html#quick-start["Dokumentation zur NetApp -Datenklassifizierung"^] :
+
... Erstellen eines Konsolenagenten
... Stellen Sie sicher, dass Ihre Umgebung die Voraussetzungen erfüllt
... Bereitstellen der NetApp Datenklassifizierung




+

NOTE: Die Datenguardrails-Funktion wird bei der Aufnahme strukturierter Datendateien wie CSV, JSON, JSONP oder Parkett nicht unterstützt.



[discrete]
===== Chat- und Abrufeinstellungen

. *Chat-Modell*:
+
** Wählen Sie aus verschiedenen Chat-Modellen, die in Amazon Bedrock integriert sind.  Beachten Sie, dass Sie das Chat-Modell von Amazon Bedrock bereits aktiviert haben müssen.
** Wählen Sie gegebenenfalls den Inferenztyp aus, der der Konfiguration des ausgewählten Modells entspricht.


. *Chat-Einstellungen*:
+
** Wählen Sie eine Temperatur für den Chatbot, um die Zufälligkeit und Kreativität der Antworten zu konfigurieren.  Eine niedrigere Temperatur führt zu vorhersehbareren Reaktionen und eine höhere Temperatur zu vielfältigeren Reaktionen.
** Wählen Sie eine maximale Antwortlänge, um zu konfigurieren, wie detailliert die Antworten sein sollen.  Längere Antwortlängen verbrauchen mehr Antworttoken und können höhere Kosten verursachen.


. *Denkmodus*: Wenn der Denkmodus aktiviert ist, benötigt der Chatbot mehr Zeit zum Verarbeiten von Anfragen und die Ergebnisse sind in der Regel genauer.  Wenn Sie den Denkmodus aktivieren, können Sie steuern, wie viele Argumentationstoken beim Generieren von Ergebnissen verwendet werden.  Die Verwendung mehrerer Argumentationstoken kann zu genaueren Antworten führen, ist jedoch möglicherweise mit höheren Kosten verbunden.
. *Neurangfolge*: Aktivieren oder deaktivieren Sie die Neurangfolge, die die Relevanz und Qualität der Abfrageergebnisse verbessern kann.  Wählen Sie für die Neubewertung ein Standard-Chat-Modell oder ein spezielles Reranker-Modell aus.  Reranker-Modelloptionen werden nur angezeigt, wenn sie in Ihrer Region verfügbar sind.  Wählen Sie den Inferenztyp aus, der der Konfiguration des ausgewählten Modells entspricht.
. *Gesprächseinstieg*: Wählen Sie aus, ob Sie bis zu vier Gesprächseinstiegstelefonate bereitstellen möchten, die Benutzern angezeigt werden, die mit einem Chatbot interagieren, der diese Wissensdatenbank nutzt. Wir empfehlen, diese Einstellung zu aktivieren.
+
Wenn Sie Gesprächseinstieg aktivieren, ist standardmäßig der automatische Modus ausgewählt. Der „manuelle Modus“ kann erst aktiviert werden, nachdem Sie Datenquellen zu Ihrer Wissensdatenbank hinzugefügt haben. link:manage-knowledgebase.html["Erfahren Sie, wie Sie die Einstellungen der Wissensdatenbank ändern"].



[discrete]
===== Speicherdefinitionen

. *FSx für ONTAP -Dateisystem*: Wenn Sie eine neue Wissensdatenbank definieren, erstellt Workload Factory ein neues Amazon FSx for NetApp ONTAP Volume, um sie zu speichern.  Wählen Sie einen vorhandenen Dateisystemnamen und eine SVM (auch Speicher-VM genannt), auf der das neue Volume erstellt wird.
. *Snapshot-Richtlinie*: Wählen Sie eine Snapshot-Richtlinie aus der Liste der vorhandenen Richtlinien aus, die im Workload Factory-Speicherinventar definiert sind.  Es werden automatisch wiederkehrende Snapshots der Wissensdatenbank in einer Häufigkeit erstellt, die auf der von Ihnen ausgewählten Snapshot-Richtlinie basiert.
. *S3-Bucket*: Wenn die Abfrageergebnisse des Chatbots strukturierte Daten enthalten, kann GenAI die Ergebnisse in einem S3-Bucket speichern.  Um diese Funktion zu verwenden, aktivieren Sie die Einstellung *S3-Bucket aktivieren* und wählen Sie aus der Liste einen S3-Bucket aus, der mit Ihrem Konto verknüpft ist.  Wenn diese Ergebnisse in einem S3-Bucket gespeichert sind, können Sie sie über den Download-Link innerhalb der Chat-Sitzung herunterladen.
+
Wenn die benötigte Snapshot-Richtlinie nicht vorhanden ist, können Sie https://docs.netapp.com/us-en/ontap/data-protection/create-snapshot-policy-task.html["Erstellen einer Snapshot-Richtlinie"] auf der Storage-VM, die das Volume enthält, arbeiten.



. Wählen Sie *Create Knowledge Base*, um die Wissensdatenbank zu GenAI hinzuzufügen.
+
Während der Erstellung der Wissensdatenbank wird ein Fortschrittsindikator angezeigt.

+
Nachdem die Wissensdatenbank erstellt wurde, haben Sie die Möglichkeit, eine Datenquelle zu Ihrer neuen Wissensdatenbank hinzuzufügen oder den Prozess zu beenden, ohne eine Datenquelle hinzuzufügen. Wir empfehlen Ihnen, *Add Data source* auszuwählen und jetzt eine oder mehrere Datenquellen hinzuzufügen.





== Fügen Sie der Wissensdatenbank Datenquellen hinzu

Sie können eine oder mehrere Datenquellen hinzufügen, um die Wissensdatenbank mit den Daten Ihres Unternehmens zu füllen.

.Über diese Aufgabe
Die maximale Anzahl unterstützter Datenquellen beträgt 10.

.Schritte
. Nachdem Sie *Datenquelle hinzufügen* ausgewählt haben, wählen Sie den Typ der Datenquelle aus, die Sie hinzufügen möchten:
+
** FSx für ONTAP-Dateisystem hinzufügen (Dateien aus einem vorhandenen FSx für ONTAP-Volume verwenden)
** Dateisystem hinzufügen (Dateien aus einer generischen SMB- oder NFS-Freigabe verwenden)




[role="tabbed-block"]
====
.Fügen Sie ein FSx für ONTAP-Dateisystem hinzu
--
. *Wählen Sie ein Dateisystem*: Wählen Sie das FSX für ONTAP Dateisystem, in dem sich Ihre Datenquelldateien befinden, und wählen Sie *Weiter*.
. *Wählen Sie ein Volume*: Wählen Sie das Volume aus, auf dem sich Ihre Quelldateien befinden, und wählen Sie *Weiter*.
+
Bei der Auswahl der mit dem SMB-Protokoll gespeicherten Dateien müssen Sie die Active Directory-Informationen eingeben, einschließlich Domäne, IP-Adresse, Benutzername und Passwort.

. *Wählen Sie eine Datenquelle*: Wählen Sie den Speicherort der Datenquelle basierend darauf, wo Sie die Dateien gespeichert haben. Dies kann ein ganzes Volume sein, oder nur ein bestimmter Ordner oder Unterordner im Volume, und wählen Sie *Weiter*.
. *Konfigurationen*: Konfigurieren Sie, wie die Datenquelle Informationen aus Ihren Dateien einliest und welche Dateien sie in Scans enthält:
+
** *Datenquelle definieren*: Definieren Sie im Abschnitt *Chunking-Strategie*, wie die GenAI-Engine den Inhalt der Datenquelle in Blöcke teilt, wenn die Datenquelle in eine Wissensdatenbank integriert ist. Sie können eine der folgenden Strategien wählen:
+
*** *Multi-Sentence Chunking*: Organisiert Informationen aus Ihrer Datenquelle in Satzbausteine. Sie können festlegen, wie viele Sätze jedes Stück ausmachen (bis zu 100).
*** *Überlappendes Chunking*: Organisiert Informationen aus Ihrer Datenquelle in zeichendefinierte Blöcke, die benachbarte Blöcke überlappen können. Sie können die Größe jedes Chunk in Zeichen auswählen und festlegen, wie viel sich jeder Chunk mit benachbarten Chunks überschneidet. Sie können eine Chunk-Größe von 50 bis 3000 Zeichen und einen Überlappungsprozentsatz von 1 bis 99 % konfigurieren.
+

NOTE: Die Auswahl eines hohen Prozentsatzes für Überschneidungen kann den Speicherbedarf erheblich erhöhen, da die Abrufgenauigkeit nur geringfügig verbessert wird.



** *Dateifilterung*: Konfigurieren Sie, welche Dateien in Scans enthalten sind:
+
*** Wählen Sie im Abschnitt *Unterstützung für Dateitypen* entweder alle Dateitypen aus oder wählen Sie einzelne Dateitypen aus, um sie in die Datenquellprüfungen einzubeziehen.
+
Wenn Sie Bilder oder PDF-Dateien einschließen, analysiert NetApp Workload Factory für GenAI den Text in den Bildern (einschließlich Bildern in PDF-Dokumenten), was höhere Kosten verursacht.

+
Beim Einbeziehen von Textdaten aus Bildern ist GenAI nicht in der Lage, personenbezogene Daten (PII) aus dem Bild zu maskieren, wenn die gescannten Textdaten aus Ihrer Umgebung an AWS gesendet werden. Sobald die Daten jedoch gespeichert sind, werden alle PII in der GenAI-Datenbank maskiert.

+

NOTE: Ihre Wahl, Bilddateien in Scans aufzunehmen, hängt mit dem Chatmodell der Wissensdatenbank zusammen. Wenn Sie Bilddateien in Scans aufnehmen, muss das Chatmodell Bilder unterstützen. Wenn hier Bilddateitypen ausgewählt sind, können Sie die Wissensdatenbank nicht auf ein Chatmodell umschalten, das keine Bilddateien unterstützt.

*** Wählen Sie im Abschnitt *Dateiänderungszeitfilter* die Option, die Aufnahme von Dateien basierend auf ihrer Änderungszeit zu aktivieren oder zu deaktivieren. Wenn Sie die Zeitfilterung für die Änderung aktivieren, wählen Sie einen Datumsbereich aus der Liste aus.
+

NOTE: Wenn Sie Dateien auf Basis eines Änderungsdatums einbeziehen, werden die Dateien aus dem periodischen Scan ausgeschlossen, und die Datenquelle enthält diese Dateien nicht, sobald der Datumsbereich nicht erfüllt ist (die Dateien wurden nicht innerhalb des von Ihnen angegebenen Datumsbereichs geändert).





. Im Abschnitt *permission aware*, der nur verfügbar ist, wenn sich die von Ihnen ausgewählte Datenquelle auf einem Volume befindet, das das SMB-Protokoll verwendet, können Sie permission-aware Antworten aktivieren oder deaktivieren:
+
** *Enabled*: Benutzer des Chatbot, die auf diese Wissensdatenbank zugreifen, erhalten nur Antworten auf Abfragen aus Datenquellen, auf die sie zugreifen können.
** *Disabled*: Benutzer des Chatbot erhalten Antworten über Inhalte aus allen integrierten Datenquellen.


. Wählen Sie *Hinzufügen*, um diese Datenquelle zu Ihrer Wissensdatenbank hinzuzufügen.


--
.Hinzufügen eines generischen NFS-Dateisystems
--
. *Wählen Sie ein Dateisystem*: Geben Sie die IP-Adresse oder den FQDN für den Dateisystem-Host ein, auf dem sich Ihre Datenquelldateien befinden, wählen Sie das NFS-Protokoll für die Netzwerkfreigabe und klicken Sie auf *Weiter*.
. *Wählen Sie eine Datenquelle*: Wählen Sie den Speicherort der Datenquelle basierend darauf, wo Sie die Dateien gespeichert haben. Dies kann ein ganzes Volume sein, oder nur ein bestimmter Ordner oder Unterordner im Volume, und wählen Sie *Weiter*.
+

NOTE: In manchen Fällen müssen Sie den NFS-Exportnamen manuell eingeben und „Verzeichnisse abrufen“ auswählen, um die verfügbaren Verzeichnisse anzuzeigen. Sie können den gesamten Export oder nur bestimmte Ordner auswählen.

. *Konfigurationen*: Konfigurieren Sie, wie die Datenquelle Informationen aus Ihren Dateien einliest und welche Dateien sie in Scans enthält:
+
** *Datenquelle definieren*: Definieren Sie im Abschnitt *Chunking-Strategie*, wie die GenAI-Engine den Inhalt der Datenquelle in Blöcke teilt, wenn die Datenquelle in eine Wissensdatenbank integriert ist. Sie können eine der folgenden Strategien wählen:
+
*** *Multi-Sentence Chunking*: Organisiert Informationen aus Ihrer Datenquelle in Satzbausteine. Sie können festlegen, wie viele Sätze jedes Stück ausmachen (bis zu 100).
*** *Überlappendes Chunking*: Organisiert Informationen aus Ihrer Datenquelle in zeichendefinierte Blöcke, die benachbarte Blöcke überlappen können. Sie können die Größe jedes Chunk in Zeichen auswählen und festlegen, wie viel sich jeder Chunk mit benachbarten Chunks überschneidet. Sie können eine Chunk-Größe von 50 bis 3000 Zeichen und einen Überlappungsprozentsatz von 1 bis 99 % konfigurieren.
+

NOTE: Die Auswahl eines hohen Prozentsatzes für Überschneidungen kann den Speicherbedarf erheblich erhöhen, da die Abrufgenauigkeit nur geringfügig verbessert wird.



** *Dateifilterung*: Konfigurieren Sie, welche Dateien in Scans enthalten sind:
+
*** Wählen Sie im Abschnitt *Unterstützung für Dateitypen* entweder alle Dateitypen aus oder wählen Sie einzelne Dateitypen aus, um sie in die Datenquellprüfungen einzubeziehen.
+
Wenn Sie Bilder oder PDF-Dateien einschließen, analysiert NetApp Workload Factory für GenAI den Text in den Bildern (einschließlich Bildern in PDF-Dokumenten), was höhere Kosten verursacht.

+
Beim Einbeziehen von Textdaten aus Bildern ist GenAI nicht in der Lage, personenbezogene Daten (PII) aus dem Bild zu maskieren, wenn die gescannten Textdaten aus Ihrer Umgebung an AWS gesendet werden. Sobald die Daten jedoch gespeichert sind, werden alle PII in der GenAI-Datenbank maskiert.

+

NOTE: Ihre Wahl, Bilddateien in Scans aufzunehmen, hängt mit dem Chatmodell der Wissensdatenbank zusammen. Wenn Sie Bilddateien in Scans aufnehmen, muss das Chatmodell Bilder unterstützen. Wenn hier Bilddateitypen ausgewählt sind, können Sie die Wissensdatenbank nicht auf ein Chatmodell umschalten, das keine Bilddateien unterstützt.

*** Wählen Sie im Abschnitt *Dateiänderungszeitfilter* die Option, die Aufnahme von Dateien basierend auf ihrer Änderungszeit zu aktivieren oder zu deaktivieren. Wenn Sie die Zeitfilterung für die Änderung aktivieren, wählen Sie einen Datumsbereich aus der Liste aus.
+

NOTE: Wenn Sie Dateien auf Basis eines Änderungsdatums einbeziehen, werden die Dateien aus dem periodischen Scan ausgeschlossen, und die Datenquelle enthält diese Dateien nicht, sobald der Datumsbereich nicht erfüllt ist (die Dateien wurden nicht innerhalb des von Ihnen angegebenen Datumsbereichs geändert).





. Wählen Sie *Datenquelle hinzufügen*, um diese Datenquelle zu Ihrer Wissensdatenbank hinzuzufügen.


--
.Hinzufügen eines generischen SMB-Dateisystems
--
. *Dateisystem auswählen*:
+
.. Geben Sie die IP-Adresse oder den FQDN für den Dateisystem-Host ein, auf dem sich Ihre Datenquelldateien befinden.
.. Wählen Sie das SMB-Protokoll für die Netzwerkfreigabe.
.. Geben Sie die Active Directory-Informationen ein, darunter Domäne, IP-Adresse, Benutzername und Kennwort.
.. Wählen Sie *Weiter*.


. *Wählen Sie eine Datenquelle*: Wählen Sie den Speicherort der Datenquelle basierend darauf, wo Sie die Dateien gespeichert haben. Dies kann ein ganzes Volume sein, oder nur ein bestimmter Ordner oder Unterordner im Volume, und wählen Sie *Weiter*.
+

NOTE: In manchen Fällen müssen Sie den Namen der SMB-Freigabe manuell eingeben und „Verzeichnisse abrufen“ auswählen, um die verfügbaren Verzeichnisse anzuzeigen. Sie können die gesamte Freigabe oder nur bestimmte Ordner darin auswählen.

. *Konfigurationen*: Konfigurieren Sie, wie die Datenquelle Informationen aus Ihren Dateien einliest und welche Dateien sie in Scans enthält:
+
** *Datenquelle definieren*: Definieren Sie im Abschnitt *Chunking-Strategie*, wie die GenAI-Engine den Inhalt der Datenquelle in Blöcke teilt, wenn die Datenquelle in eine Wissensdatenbank integriert ist. Sie können eine der folgenden Strategien wählen:
+
*** *Multi-Sentence Chunking*: Organisiert Informationen aus Ihrer Datenquelle in Satzbausteine. Sie können festlegen, wie viele Sätze jedes Stück ausmachen (bis zu 100).
*** *Überlappendes Chunking*: Organisiert Informationen aus Ihrer Datenquelle in zeichendefinierte Blöcke, die benachbarte Blöcke überlappen können. Sie können die Größe jedes Chunk in Zeichen auswählen und festlegen, wie viel sich jeder Chunk mit benachbarten Chunks überschneidet. Sie können eine Chunk-Größe von 50 bis 3000 Zeichen und einen Überlappungsprozentsatz von 1 bis 99 % konfigurieren.
+

NOTE: Die Auswahl eines hohen Prozentsatzes für Überschneidungen kann den Speicherbedarf erheblich erhöhen, da die Abrufgenauigkeit nur geringfügig verbessert wird.



** *Berechtigungsbewusst*: Aktivieren oder deaktivieren Sie berechtigungsbewusste Antworten:
+
*** *Enabled*: Benutzer des Chatbot, die auf diese Wissensdatenbank zugreifen, erhalten nur Antworten auf Abfragen aus Datenquellen, auf die sie zugreifen können.
*** *Disabled*: Benutzer des Chatbot erhalten Antworten über Inhalte aus allen integrierten Datenquellen.


** *Dateifilterung*: Konfigurieren Sie, welche Dateien in Scans enthalten sind:
+
*** Wählen Sie im Abschnitt *Unterstützung für Dateitypen* entweder alle Dateitypen aus oder wählen Sie einzelne Dateitypen aus, um sie in die Datenquellprüfungen einzubeziehen.
+
Wenn Sie Bilder oder PDF-Dateien einschließen, analysiert NetApp Workload Factory für GenAI den Text in den Bildern (einschließlich Bildern in PDF-Dokumenten), was höhere Kosten verursacht.

+
Beim Einbeziehen von Textdaten aus Bildern ist GenAI nicht in der Lage, personenbezogene Daten (PII) aus dem Bild zu maskieren, wenn die gescannten Textdaten aus Ihrer Umgebung an AWS gesendet werden. Sobald die Daten jedoch gespeichert sind, werden alle PII in der GenAI-Datenbank maskiert.

+

NOTE: Ihre Wahl, Bilddateien in Scans aufzunehmen, hängt mit dem Chatmodell der Wissensdatenbank zusammen. Wenn Sie Bilddateien in Scans aufnehmen, muss das Chatmodell Bilder unterstützen. Wenn hier Bilddateitypen ausgewählt sind, können Sie die Wissensdatenbank nicht auf ein Chatmodell umschalten, das keine Bilddateien unterstützt.

*** Wählen Sie im Abschnitt *Dateiänderungszeitfilter* die Option, die Aufnahme von Dateien basierend auf ihrer Änderungszeit zu aktivieren oder zu deaktivieren. Wenn Sie die Zeitfilterung für die Änderung aktivieren, wählen Sie einen Datumsbereich aus der Liste aus.
+

NOTE: Wenn Sie Dateien auf Basis eines Änderungsdatums einbeziehen, werden die Dateien aus dem periodischen Scan ausgeschlossen, und die Datenquelle enthält diese Dateien nicht, sobald der Datumsbereich nicht erfüllt ist (die Dateien wurden nicht innerhalb des von Ihnen angegebenen Datumsbereichs geändert).





. Wählen Sie *Datenquelle hinzufügen*, um diese Datenquelle zu Ihrer Wissensdatenbank hinzuzufügen.


--
====
.Ergebnis
Die Datenquelle wird in Ihre Wissensdatenbank eingebettet. Der Status ändert sich von „Einbetten“ in „eingebettet“, wenn die Datenquelle vollständig eingebettet ist.

Nachdem Sie der Wissensdatenbank eine einzelne Datenquelle hinzugefügt haben, können Sie diese lokal im Chatbot-Simulator testen und alle erforderlichen Änderungen vornehmen, bevor Sie den Chatbot Ihren Benutzern zur Verfügung stellen. Sie können die gleichen Schritte ausführen, um der Wissensdatenbank zusätzliche Datenquellen hinzuzufügen.
