---
sidebar: sidebar 
permalink: knowledge-base/requirements-knowledge-base.html 
keywords: ai, chatbot, prerequisites, bedrock, fsx for ontap, prerequisites, requirements 
summary: Stellen Sie sicher, dass die Workload-Fabrik und AWS ordnungsgemäß eingerichtet sind, bevor Sie Ihre Knowledge Base aufbauen. Dazu gehören die Zugangsdaten für die AWS-Anmeldung, ein bereitgestelltes FSX für ONTAP-Filesystem mit den Datenquellen, die Sie in Ihre Wissensdatenbank integrieren möchten, Zugriff auf den Amazon Bedrock KI-Service und vieles mehr. 
---
= Anforderungen der GenAI Knowledge Base
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Stellen Sie sicher, dass die Workload-Fabrik und AWS ordnungsgemäß eingerichtet sind, bevor Sie Ihre Knowledge Base aufbauen. Dazu gehören die Zugangsdaten für die AWS-Anmeldung, ein bereitgestelltes FSX für ONTAP-Filesystem mit den Datenquellen, die Sie in Ihre Wissensdatenbank integrieren möchten, Zugriff auf den Amazon Bedrock KI-Service und vieles mehr.



== Grundlegende GenAI-Anforderungen

Für GenAI gelten allgemeine Anforderungen, die Ihre Umgebung vor der Inbetriebnahme erfüllen muss.

Workload Werksanmeldung und Konto:: Sie müssen https://docs.netapp.com/us-en/workload-setup-admin/sign-up-saas.html["Richten Sie ein Konto mit Workload Factory ein"^] sich mit einem der anmelden https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^].
AWS Zugangsdaten und Berechtigungen:: Sie müssen der Workload Factory AWS-Anmeldeinformationen mit Lese-/Schreibberechtigungen hinzufügen. Dies bedeutet, dass Sie die Workload Factory für GenAI im Lese-/Schreibmodus verwenden.
+
--
_Basic_ Mode und _Read-Only_ Mode Berechtigungen werden derzeit nicht unterstützt.

Wenn Sie Ihre Anmeldedaten einrichten, erhalten Sie durch die Auswahl der unten aufgeführten Berechtigungen vollständigen Zugriff auf das Management von FSX für ONTAP-Dateisysteme sowie auf die Bereitstellung und das Management der GenAI EC2-Instanz und anderer AWS-Ressourcen, die für Ihre Knowledge Base und Ihren Chatbot benötigt werden.

https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Erfahren Sie, wie Sie AWS-Anmeldedaten zu der Workload-Farm hinzufügen"^]

--




== Anforderungen der GenAI Knowledge Base

Wenn Sie mit Wissensdatenbanken arbeiten möchten, stellen Sie sicher, dass Ihre Umgebung die folgenden Anforderungen erfüllt.

Amazonas-Grundgestein:: Mit Amazon Bedrock können Sie Grundmodelle verwenden und es bietet die Möglichkeiten, generative KI-Anwendungen zu erstellen.
+
--
Bevor Sie mit der BlueXP -Workload-Fabrik für GenAI beginnen, müssen Sie Amazon Bedrock einrichten. Ihre GenAI-Implementierung muss sich in einer AWS-Region mit aktiviertem Amazon Bedrock befinden.

* https://docs.aws.amazon.com/bedrock/latest/userguide/setting-up.html["AWS-Dokumentation: Einrichten von Amazon Bedrock"^]
* https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base-supported.html["AWS-Dokumentation: Unterstützte Regionen und Modelle für Knowledge Basen für Amazon Bedrock"^]


GenAI ordnet die Suchergebnisse standardmäßig neu ein, um die Relevanz der Ergebnisse zu verbessern. Um die besten Ergebnisse zu erzielen, stellen Sie sicher, dass Ihre Konfiguration des Basismodells Amazon Bedrock den Zugriff auf ein neues Modell wie Cohere Rerank oder Amazon Rerank umfasst, falls es in Ihrer Region verfügbar ist.

--
Einbettungsmodell:: Sie müssen das einzubetende Modell aktivieren, das Sie verwenden möchten, bevor Sie Ihre Wissensdatenbank erstellen. Die folgenden Einbettungsmodelle werden unterstützt:
+
--
* Titan-Einbauteile G1 - Text
* Titan Einbettung Text v2
* Titan Multimodal Embeddings G1
* Englisch Einbetten
* Mehrsprachig Einbetten
+
https://aws.amazon.com/bedrock/titan/["Erfahren Sie mehr über Amazon Titan"^]



--
Chat-Modell:: Sie müssen das grundlegende Chatmodell aktivieren, das Sie verwenden möchten, bevor Sie Ihre Wissensdatenbank erstellen. Da der Modellsupport je nach AWS-Region variiert, finden Sie unter https://docs.aws.amazon.com/bedrock/latest/userguide/models-regions.html["Die AWS Dokumentation"^] Informationen dazu, welche Modelle in den Regionen verwendet werden können, in denen Sie Ihre Knowledge Base bereitstellen möchten.
+
--
GenAI unterstützt verschiedene Modelle von Anthropic, Amazon, Mistral AI, Meta, Jamba und Cohhere.

Erfahren Sie mehr über die Verwendung dieser Modelle in Amazon Bedrock:

* https://aws.amazon.com/bedrock/claude/["Anthropic's Claude in Amazon Bedrock"^]
* https://docs.aws.amazon.com/nova/latest/userguide/getting-started-console.html["Erste Schritte mit Amazon Nova in der Amazon Bedrock Konsole"^]
* https://aws.amazon.com/bedrock/mistral/["Mistral KI-Modelle"^]
* https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon Titan Textmodelle"^]
* https://aws.amazon.com/bedrock/llama/["Meta Llama Modelle"^]
* https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-jamba.html["Jamba-Modelle"^]
* https://aws.amazon.com/bedrock/cohere/["Co-here Command-Modelle"^]


--
FSX für ONTAP-Dateisystem:: Sie benötigen mindestens ein FSX für ONTAP-Dateisystem:
+
--
* Ein Dateisystem wird von der NetApp GenAI-Engine verwendet (oder erstellt, falls es nicht existiert), um die von der Wissensdatenbank verwendete Vektordatenbank zu speichern.
+
Dieses Dateisystem FSX für ONTAP muss FlexVol-Volumen verwenden. FlexGroup Volumes werden nicht unterstützt.

* Ein oder mehrere Dateisysteme enthalten die Datenquellen, die Sie in Ihre Wissensdatenbank integrieren werden.
+
Ein FSX für ONTAP-Dateisystem kann für beide dieser Zwecke verwendet werden, oder Sie können mehrere FSX für ONTAP-Dateisysteme verwenden.

* Sie müssen die AWS-Region, VPC und das Subnetz kennen, in der sich das AWS FSX für ONTAP-Filesystem befindet. Das Filesystem muss sich in einer AWS-Region befinden, für die Amazon Bedrock aktiviert ist.
* Sie müssen die Tag-Schlüssel-/Wertpaare berücksichtigen, die Sie auf die AWS Ressourcen anwenden möchten, die Teil dieser Implementierung sind (optional).
* Dabei sind die wichtigsten Paar-Informationen wichtig, die eine sichere Verbindung zur NetApp AI Engine-Instanz ermöglichen.


https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Erfahren Sie, wie Sie FSX für ONTAP-Dateisysteme implementieren und managen"^]

--

