---
sidebar: sidebar 
permalink: knowledge-base/whats-next.html 
keywords: what you can do, knowledge base 
summary: Nachdem Sie jetzt eine Wissensdatenbank mit Ihren Unternehmensdaten erstellt und für Ihre Benutzer bereitgestellt haben, können Sie die Wissensdatenbank, Datenquellen und die RAG-Infrastruktur, einschließlich FSX für ONTAP-Dateisysteme, verwalten. 
---
= Was Sie mit GenAI erreichen können
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie jetzt eine Wissensdatenbank mit Ihren Unternehmensdaten erstellt und für Ihre Benutzer bereitgestellt haben, können Sie die Wissensdatenbank, Datenquellen und die RAG-Infrastruktur, einschließlich FSX für ONTAP-Dateisysteme, verwalten.

Einige der Aufgaben, die Sie zur Verwaltung Ihrer Knowledge-Base-Komponenten durchführen können, sind:

* Aktualisieren Sie den Inhalt Ihrer Datenquellen, oder fügen Sie neue Datenquellen hinzu, und synchronisieren Sie diese Änderungen mit Ihrer Wissensdatenbank und Ihrem Chatbot.
* Managen Sie Ihre Datenquelleinstellungen, einschließlich der Chunking-Strategie und Berechtigungsorientierung (für SMB-Dateizugriff).
* Verwalten Sie Ihre Knowledge Base-Einstellungen, einschließlich Chat-Modell und Gesprächseinstieg.
* Heben Sie die Veröffentlichung einer Wissensdatenbank auf, oder veröffentlichen Sie sie erneut, nachdem Sie Änderungen vorgenommen haben.
* Sichern und schützen Sie die wichtigen Daten auf Ihrem FSX für ONTAP-Dateisystem, um sicherzustellen, dass Ihre Wissensdatenbank-Daten und andere Infrastrukturkomponenten immer verfügbar sind.


Informationen zum Verwalten Ihres FSX für ONTAP-Dateisystems finden Sie unter, um die https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Workload-Fabrik für Amazon FSX für NetApp ONTAP-Dokumentation"^] Backup- und Schutzfunktionen anzuzeigen, die Sie verwenden können.
