---
sidebar: sidebar 
permalink: connector/define-connector.html 
keywords: ai, chatbot, connector, 
summary: Nachdem Sie die KI-Infrastruktur bereitgestellt und die Datenquellen identifiziert haben, die Sie in Amazon Q Business integrieren möchten, können Sie einen Connector definieren. 
---
= Erstellen Sie einen NetApp Connector für Amazon Q Business
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die KI-Infrastruktur bereitgestellt und die Datenquellen identifiziert haben, die Sie aus Ihren FSx für ONTAP-Datenspeichern verwenden werden, können Sie einen NetApp Connector für Amazon Q Business definieren.

Stellen Sie sicher, dass Ihre Umgebung den  für Amazon Q Business erfülltlink:requirements-connector.html["Anforderungen"], bevor Sie fortfahren.

.Über diese Aufgabe
Datenquellen Ihrer Organisation können personenbezogene Daten (PII) enthalten.  Um diese vertraulichen Informationen zu schützen, können Sie beim Definieren eines Connectors _Datenleitplanken_ aktivieren.  Datenleitplanken, unterstützt durch NetApp Data Classification, identifizieren und maskieren personenbezogene Daten und machen sie so unzugänglich und unwiederbringlich.

link:https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["Erfahren Sie mehr über die NetApp Datenklassifizierung"^] .


NOTE: NetApp Workload Factory für GenAI maskiert keine sensiblen persönlichen Informationen (SPII).  Siehelink:https://docs.netapp.com/us-en/data-services-data-classification/reference-private-data-categories.html#types-of-sensitive-personal-data["Arten sensibler personenbezogener Daten"^] für weitere Informationen zu dieser Art von Daten.


NOTE: Datenleitplanken können jederzeit aktiviert oder deaktiviert werden.  Wenn Sie die Aktivierung von Datenleitplanken ändern, scannt Workload Factory die gesamte Datenquelle von Grund auf, was Kosten verursachen kann.



== Definieren Sie einen Konnektor

Erstellen Sie einen NetApp-Connector für Amazon Q Business. Der Connector ermöglicht die API- und Datenquellenkommunikation zwischen GenAI und Amazon Q Business.

.Schritte
. Melden Sie sich bei Workload Factory mit einem der folgendenlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["Konsolenerfahrungen"^] .
. Wählen Sie in der Kachel AI-Workloads *Deploy & manage* aus.
. Wählen Sie im Menü „Wissensdatenbanken und Konnektoren“ das Dropdown-Menü „Neu erstellen“ und wählen Sie „Amazon Q Business Connector“ aus.
. Konfigurieren Sie auf der Seite Konnektor definieren die Verbindungseinstellungen:
+
.. *Name*: Geben Sie den Namen ein, den Sie für den Konnektor verwenden möchten.
.. *Beschreibung*: Geben Sie eine detaillierte Beschreibung für den Konnektor ein.
.. *Amazon Q*: Die Region und der Anwendungsname für die Amazon Q Business Instanz, die Sie integrieren möchten.
.. *Datenleitplanken*: Wählen Sie, ob Sie Datenleitplanken aktivieren oder deaktivieren möchten. link:https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["Erfahren Sie mehr über Datenleitplanken, unterstützt durch NetApp Data Classification"^] .
+
Die folgenden Voraussetzungen müssen erfüllt sein, um die Data Guardrails zu aktivieren.

+
*** Für die Kommunikation mit NetApp Data Classification ist ein Servicekonto erforderlich.  Für die Erstellung eines Dienstkontos müssen Sie in Ihrem NetApp Console-Mandantenkonto über die Rolle „Organisationsadministrator“ verfügen.  Ein Mitglied mit der Rolle „Organisationsadministrator“ kann alle Aktionen in der NetApp Konsole ausführen.link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html#add-a-role-to-a-member["Erfahren Sie, wie Sie einem Mitglied in der NetApp -Konsole eine Rolle hinzufügen"^]
*** Die KI-Engine muss Zugriff auf dielink:https://api.bluexp.netapp.com["NetApp Console API-Endpunkt"^] .
*** Sie müssen Folgendes tun, wie inlink:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-cloud-compliance.html#quick-start["Dokumentation zur NetApp -Datenklassifizierung"^] :
+
.... Erstellen eines Konsolenagenten
.... Stellen Sie sicher, dass Ihre Umgebung die Voraussetzungen erfüllt
.... Bereitstellen der NetApp Datenklassifizierung






+

NOTE: Wenn Sie die Funktion „Data Guardrails“ aktivieren, verarbeitet GenAI die Dateien .txt, .md, .csv, .docx und .pdf, indem nur Klartext (ohne eingebetteten Bild- oder Medientext) aufgenommen und private oder sensible Daten maskiert werden. Alle anderen Dateitypen werden normal verarbeitet, ohne dass private oder sensible Daten maskiert werden.

+
.. *FSx für ONTAP Dateisystem*: Wenn Sie einen neuen NetApp Connector für Amazon Q Business definieren, erstellt Workload Factory ein neues Amazon FSx for NetApp ONTAP -Volume zum Speichern der Connector-Informationen.  Wählen Sie ein vorhandenes Dateisystem und eine SVM (auch Speicher-VM genannt), auf der das neue Volume erstellt wird.
.. *Snapshot-Richtlinie*: Wählen Sie eine Snapshot-Richtlinie aus der Liste der vorhandenen Richtlinien aus, die im Workload Factory-Speicherinventar definiert sind.  GenAI erstellt automatisch wiederkehrende Snapshots des Volumes, in denen die Connector-Informationen gespeichert sind, und zwar in einer Häufigkeit, die auf der von Ihnen ausgewählten Snapshot-Richtlinie basiert.
+
Wenn die benötigte Snapshot-Richtlinie nicht vorhanden ist, können Sie https://docs.netapp.com/us-en/ontap/data-protection/create-snapshot-policy-task.html["Erstellen einer Snapshot-Richtlinie"^] auf der Storage-VM, die das Volume enthält, arbeiten.



. Wählen Sie *Create Connector*, um Amazon Q Business mit GenAI zu integrieren.
+
Während der Verbindungserstellung wird eine Fortschrittsanzeige angezeigt.

+
Nachdem der Connector erstellt wurde, haben Sie die Möglichkeit, dem Connector eine Datenquelle hinzuzufügen, sodass Amazon Q Business Ihre Daten aufnimmt und zu seinem Index hinzufügt. Wir empfehlen Ihnen, *Add Data source* auszuwählen und jetzt eine oder mehrere Datenquellen hinzuzufügen.





== Fügen Sie dem Connector Datenquellen hinzu

Sie können eine oder mehrere Datenquellen hinzufügen, um den Amazon Q Business Index mit den Daten Ihres Unternehmens zu füllen.

.Über diese Aufgabe
* Die maximale Anzahl unterstützter Datenquellen beträgt 10.
* In https://docs.aws.amazon.com/kendra/latest/dg/quotas.html["Amazon Q Business-Dokumentation"^] finden Sie spezifische Serviceeinschränkungen des Amazon Q Business Index.


.Schritte
. Nachdem Sie *Datenquelle hinzufügen* ausgewählt haben, wird die Seite *Dateisystem auswählen* angezeigt.
. *Wählen Sie ein Dateisystem*: Wählen Sie das FSX für ONTAP Dateisystem, in dem sich Ihre Datenquelldateien befinden, und wählen Sie *Weiter*.
. *Wählen Sie ein Volume*: Wählen Sie das Volume aus, auf dem sich Ihre Quelldateien befinden, und wählen Sie *Weiter*.
+
Bei der Auswahl der mit dem SMB-Protokoll gespeicherten Dateien müssen Sie die Active Directory-Informationen eingeben, einschließlich Domäne, IP-Adresse, Benutzername und Passwort.

. *Wählen Sie eine Datenquelle*: Wählen Sie den Speicherort der Datenquelle basierend darauf, wo Sie die Dateien gespeichert haben. Dies kann ein ganzes Volume sein, oder nur ein bestimmter Ordner oder Unterordner im Volume, und wählen Sie *Weiter*.
. *Konfigurationen*: Konfigurieren Sie, wie die Datenquelle Informationen aus Ihren Dateien einliest und welche Dateien sie in Scans enthält:
+
** *Dateifilterung*: Konfigurieren Sie, welche Dateien in Scans enthalten sind:
+
*** Wählen Sie im Abschnitt *Unterstützung für Dateitypen* entweder alle Dateitypen aus oder wählen Sie einzelne Dateitypen aus, um sie in die Datenquellprüfungen einzubeziehen.
*** Wählen Sie im Abschnitt *Dateiänderungszeitfilter* die Option, die Aufnahme von Dateien basierend auf ihrer Änderungszeit zu aktivieren oder zu deaktivieren. Wenn Sie die Zeitfilterung für die Änderung aktivieren, wählen Sie einen Datumsbereich aus der Liste aus.
+

NOTE: Wenn Sie Dateien auf Basis eines Änderungsdatums einbeziehen, werden die Dateien aus dem periodischen Scan ausgeschlossen, und die Datenquelle enthält diese Dateien nicht, sobald der Datumsbereich nicht erfüllt ist (die Dateien wurden nicht innerhalb des von Ihnen angegebenen Datumsbereichs geändert).





. Im Abschnitt *permission aware*, der nur verfügbar ist, wenn sich die von Ihnen ausgewählte Datenquelle auf einem Volume befindet, das das SMB-Protokoll verwendet, können Sie permission-aware Antworten aktivieren oder deaktivieren:
+
** *Enabled*: Benutzer des Chatbot, die auf diesen Konnektor zugreifen, erhalten nur Antworten auf Abfragen aus Datenquellen, auf die sie Zugriff haben.
** *Disabled*: Benutzer des Chatbot erhalten Antworten über Inhalte aus allen integrierten Datenquellen.
+

NOTE: Active Directory-Gruppenberechtigungen werden für Datenquellen des Amazon Q Business Connectors nicht unterstützt.



. Wählen Sie *Hinzufügen*, um diese Datenquelle zum Amazon Q Business Connector hinzuzufügen.


.Ergebnis
Die Datenquelle ist in den Amazon Q Business Index eingebettet. Der Status ändert sich von „Einbetten“ in „eingebettet“, wenn die Datenquelle vollständig eingebettet ist.

Nachdem Sie dem Connector eine einzelne Datenquelle hinzugefügt haben, können Sie diese in der Chatbot-Umgebung von Amazon Q Business testen und alle erforderlichen Änderungen vornehmen, bevor Sie den Dienst Ihren Benutzern zur Verfügung stellen. Sie können auch die gleichen Schritte ausführen, um dem Connector zusätzliche Datenquellen hinzuzufügen.
